pipeline 
{
    agent any
    stages
    {
        stage ('checkout the code')
        {
            steps
            {
                git(url: 'https://github.com/diptishegar/Expenses-Tracker-WebApp.git', branch: 'main')
            }
        }
        post {
            success {
                echo 'Image Built Successfully'
            } failure {
                echo 'Image Build Failed'
            }
        }
    }
}
