pipeline 
{
    agent any
    environment {
        DOCKER_HUB_CREDENTIALS = credentials('docker-hub-credentials')
    }
    stages
    {
        stage ('checkout the code') {
            steps {
                git(url: 'https://github.com/diptishegar/Expenses-Tracker-WebApp.git', branch: 'main')
            }
        }
        stage ('Build Image')
        {
            steps
            {
                script {
                    dockerImage = docker.build("diptishegar/expenses-tracker-webapp:${env.BUILD_ID}")
                }
            }
        } 
        stage ('Push Image to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('', DOCKER_HUB_CREDENTIALS) {
                        dockerImage.push()
                    }
                }
            }
        }
    }
}
